services:
  adribot_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: adribot_db
    environment:
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    secrets:
      - db_password
    healthcheck:
      test: ["/bin/sh", "sqlcmd -S localhost -U SA -P $(cat /run/secrets/db_password) -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  bot:
    image: adribot_backend
    container_name: adribot_backend
    depends_on:
      adribot_db:
        condition: service_healthy
    environment:
      DISCORD_EMBED_COLOUR: "0x191970"
      DEV_ID: 135081249017430016
      DB_CONNECTION: /run/secrets/db_connection
      CAT_TOKEN: /run/secrets/cat_token
      BOT_TOKEN: /run/secrets/bot_token
    volumes:
      - ./Adribot.App:/Adribot
    build:
      context: ./Adribot.App
      dockerfile: Dockerfile
      args:
        DB_CONNECTION: /run/secrets/db_connection
    secrets:
      - db_connection
      - cat_token
      - bot_token

secrets:
  db_password:
    file: ./Secrets/db_password.txt
  db_connection:
    file: ./Secrets/db_connection.txt
  cat_token:
    file: ./Secrets/cat_token.txt
  bot_token:
    file: ./Secrets/bot_token.txt
