services:
  adribot_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: adribot_db
    environment:
      MSSQL_SA_PASSWORD: ${db_password}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P $MSSQL_SA_PASSWORD -Q 'SELECT 1' -C",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  bot:
    container_name: adribot_backend
    depends_on:
      adribot_db:
        condition: service_healthy
    environment:
      DISCORD_EMBED_COLOUR: "FF191970"
      DEV_ID: 135081249017430016
      DB_CONNECTION: ${db_connection}
      CAT_TOKEN: ${cat_token}
      BOT_TOKEN: ${bot_token}
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
    volumes:
      - ./Adribot.App:/Adribot
    build:
      context: ./Adribot.App
      dockerfile: Dockerfile
